<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="5" failures="0" name="com.excilys.computerdatabase.service.ServiceTest" time="150.604" errors="5" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/home/excilys/Bureau/eclipse/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.77-b03"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="FR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/excilys/workspace/projetloic"/>
    <property name="java.runtime.version" value="1.8.0_77-b03"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/home/excilys/Bureau/eclipse/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/home/excilys/workspace/.metadata/.plugins/org.eclipse.m2e.launching/launches/m2conf4154829355151398645.tmp"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="4.2.0-36-generic"/>
    <property name="user.home" value="/home/excilys"/>
    <property name="user.timezone" value="Europe/Paris"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="excilys"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/home/excilys/Bureau/eclipse/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher -B test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="fr"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_77"/>
    <property name="java.ext.dirs" value="/home/excilys/Bureau/eclipse/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/home/excilys/Bureau/eclipse/jre/lib/resources.jar:/home/excilys/Bureau/eclipse/jre/lib/rt.jar:/home/excilys/Bureau/eclipse/jre/lib/sunrsasign.jar:/home/excilys/Bureau/eclipse/jre/lib/jsse.jar:/home/excilys/Bureau/eclipse/jre/lib/jce.jar:/home/excilys/Bureau/eclipse/jre/lib/charsets.jar:/home/excilys/Bureau/eclipse/jre/lib/jfr.jar:/home/excilys/Bureau/eclipse/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase classname="com.excilys.computerdatabase.service.ServiceTest" name="createComputerErrorDate" time="30.222">
    <error message="Unexpected exception, expected&lt;com.excilys.computerdatabase.exception.ServiceException&gt; but was&lt;com.zaxxer.hikari.pool.HikariPool$PoolInitializationException&gt;" type="java.lang.Exception">java.lang.Exception: Unexpected exception, expected&lt;com.excilys.computerdatabase.exception.ServiceException&gt; but was&lt;com.zaxxer.hikari.pool.HikariPool$PoolInitializationException&gt;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:524)
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:118)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at com.excilys.computerdatabase.persistence.SQLUtils.getConnection(SQLUtils.java:67)
	at com.excilys.computerdatabase.persistence.EntityDB.connect(EntityDB.java:57)
	at com.excilys.computerdatabase.persistence.ComputerDB.create(ComputerDB.java:36)
	at com.excilys.computerdatabase.service.ServiceComputer.create(ServiceComputer.java:87)
	at com.excilys.computerdatabase.service.ServiceTest.createComputerErrorDate(ServiceTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:21)
	... 21 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
	... 37 more
	Suppressed: java.lang.NullPointerException
		at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:219)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518)
		... 37 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:298)
	... 53 more
</error>
    <system-out>17:25:32.598 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
17:25:32.608 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
17:25:32.608 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
17:25:32.608 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................null
17:25:32.609 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
17:25:32.609 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............null
17:25:32.609 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
17:25:32.609 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................null
17:25:32.609 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
17:25:32.609 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
17:25:32.609 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=&lt;masked&gt;}
17:25:32.610 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................null
17:25:32.610 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
17:25:32.610 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
17:25:32.610 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
17:25:32.610 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
17:25:32.610 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
17:25:32.611 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
17:25:32.611 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................&quot;jdbc:mysql://172.20.0.50:3306/computer-database-db?zeroDateTimeBehavior=convertToNull&quot;
17:25:32.611 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
17:25:32.611 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
17:25:32.611 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................1000
17:25:32.612 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................null
17:25:32.612 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
17:25:32.612 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................1000
17:25:32.612 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................&lt;masked&gt;
17:25:32.612 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................&quot;HikariPool-1&quot;
17:25:32.613 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
17:25:32.613 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
17:25:32.613 [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
17:25:32.613 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................null
17:25:32.614 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............null
17:25:32.614 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................&quot;admincdb&quot;
17:25:32.614 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
17:25:32.614 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
17:26:02.803 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
17:26:02.803 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before closing stats (total=0, active=0, idle=0, waiting=0)
17:26:02.804 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After closing stats (total=0, active=0, idle=0, waiting=0)
17:26:02.805 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Closed.
</system-out>
  </testcase>
  <testcase classname="com.excilys.computerdatabase.service.ServiceTest" name="updateComputerErrorDate" time="30.059">
    <error message="Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server." type="com.zaxxer.hikari.pool.HikariPool$PoolInitializationException">com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:524)
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:118)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at com.excilys.computerdatabase.persistence.SQLUtils.getConnection(SQLUtils.java:67)
	at com.excilys.computerdatabase.persistence.EntityDB.connect(EntityDB.java:57)
	at com.excilys.computerdatabase.persistence.ComputerDB.update(ComputerDB.java:79)
	at com.excilys.computerdatabase.service.ServiceComputer.update(ServiceComputer.java:53)
	at com.excilys.computerdatabase.service.ServiceTest.updateComputerErrorDate(ServiceTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
	... 36 more
	Suppressed: java.lang.NullPointerException
		at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:219)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518)
		... 36 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:298)
	... 52 more
</error>
    <system-out>17:26:02.809 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
17:26:02.811 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
17:26:02.811 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
17:26:02.811 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................null
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............null
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................null
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=&lt;masked&gt;}
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................null
17:26:02.812 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................&quot;jdbc:mysql://172.20.0.50:3306/computer-database-db?zeroDateTimeBehavior=convertToNull&quot;
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
17:26:02.813 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
17:26:02.814 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................1000
17:26:02.814 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................null
17:26:02.814 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
17:26:02.814 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................1000
17:26:02.814 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................&lt;masked&gt;
17:26:02.814 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................&quot;HikariPool-1&quot;
17:26:02.814 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
17:26:02.815 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
17:26:02.815 [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
17:26:02.815 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................null
17:26:02.815 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............null
17:26:02.815 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................&quot;admincdb&quot;
17:26:02.815 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
17:26:02.815 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
17:26:32.838 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
17:26:32.838 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before closing stats (total=0, active=0, idle=0, waiting=0)
17:26:32.838 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After closing stats (total=0, active=0, idle=0, waiting=0)
17:26:32.839 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Closed.
</system-out>
  </testcase>
  <testcase classname="com.excilys.computerdatabase.service.ServiceTest" name="findComputerByName" time="30.031">
    <error message="Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server." type="com.zaxxer.hikari.pool.HikariPool$PoolInitializationException">com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:524)
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:118)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at com.excilys.computerdatabase.persistence.SQLUtils.getConnection(SQLUtils.java:67)
	at com.excilys.computerdatabase.persistence.EntityDB.connect(EntityDB.java:57)
	at com.excilys.computerdatabase.persistence.ComputerDB.findByName(ComputerDB.java:150)
	at com.excilys.computerdatabase.service.ServiceComputer.findByName(ServiceComputer.java:121)
	at com.excilys.computerdatabase.service.ServiceTest.findComputerByName(ServiceTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
	... 36 more
	Suppressed: java.lang.NullPointerException
		at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:219)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518)
		... 36 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:298)
	... 52 more
</error>
    <system-out>17:26:32.872 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
17:26:32.874 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
17:26:32.874 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
17:26:32.874 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................null
17:26:32.874 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
17:26:32.875 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............null
17:26:32.875 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
17:26:32.875 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................null
17:26:32.875 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
17:26:32.875 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
17:26:32.875 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=&lt;masked&gt;}
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................null
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
17:26:32.876 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................&quot;jdbc:mysql://172.20.0.50:3306/computer-database-db?zeroDateTimeBehavior=convertToNull&quot;
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................1000
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................null
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................1000
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................&lt;masked&gt;
17:26:32.877 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................&quot;HikariPool-1&quot;
17:26:32.878 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
17:26:32.878 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
17:26:32.878 [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
17:26:32.878 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................null
17:26:32.878 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............null
17:26:32.878 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................&quot;admincdb&quot;
17:26:32.878 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
17:26:32.879 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
17:27:02.899 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
17:27:02.900 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before closing stats (total=0, active=0, idle=0, waiting=0)
17:27:02.900 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After closing stats (total=0, active=0, idle=0, waiting=0)
17:27:02.900 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Closed.
</system-out>
  </testcase>
  <testcase classname="com.excilys.computerdatabase.service.ServiceTest" name="testCount" time="30.046">
    <error message="Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server." type="com.zaxxer.hikari.pool.HikariPool$PoolInitializationException">com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:524)
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:118)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at com.excilys.computerdatabase.persistence.SQLUtils.getConnection(SQLUtils.java:67)
	at com.excilys.computerdatabase.persistence.EntityDB.connect(EntityDB.java:57)
	at com.excilys.computerdatabase.persistence.ComputerDB.count(ComputerDB.java:383)
	at com.excilys.computerdatabase.service.ServiceComputer.count(ServiceComputer.java:104)
	at com.excilys.computerdatabase.service.ServiceTest.testCount(ServiceTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
	... 36 more
	Suppressed: java.lang.NullPointerException
		at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:219)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518)
		... 36 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:298)
	... 52 more
</error>
    <system-out>17:27:02.902 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
17:27:02.904 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
17:27:02.904 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
17:27:02.904 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................null
17:27:02.904 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
17:27:02.904 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............null
17:27:02.905 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
17:27:02.905 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................null
17:27:02.909 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
17:27:02.909 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
17:27:02.909 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=&lt;masked&gt;}
17:27:02.909 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................null
17:27:02.909 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................&quot;jdbc:mysql://172.20.0.50:3306/computer-database-db?zeroDateTimeBehavior=convertToNull&quot;
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................1000
17:27:02.910 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................null
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................1000
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................&lt;masked&gt;
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................&quot;HikariPool-1&quot;
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................null
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............null
17:27:02.911 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................&quot;admincdb&quot;
17:27:02.912 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
17:27:02.912 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
17:27:32.943 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
17:27:32.943 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before closing stats (total=0, active=0, idle=0, waiting=0)
17:27:32.943 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After closing stats (total=0, active=0, idle=0, waiting=0)
17:27:32.943 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Closed.
</system-out>
  </testcase>
  <testcase classname="com.excilys.computerdatabase.service.ServiceTest" name="createComputer" time="30.025">
    <error message="Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server." type="com.zaxxer.hikari.pool.HikariPool$PoolInitializationException">com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:524)
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:118)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at com.excilys.computerdatabase.persistence.SQLUtils.getConnection(SQLUtils.java:67)
	at com.excilys.computerdatabase.persistence.EntityDB.connect(EntityDB.java:57)
	at com.excilys.computerdatabase.persistence.ComputerDB.findAll(ComputerDB.java:238)
	at com.excilys.computerdatabase.service.ServiceComputer.findAll(ServiceComputer.java:39)
	at com.excilys.computerdatabase.service.ServiceTest.createComputer(ServiceTest.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
	... 36 more
	Suppressed: java.lang.NullPointerException
		at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:219)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518)
		... 36 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:298)
	... 52 more
</error>
    <system-out>17:27:32.945 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................null
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............null
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................null
17:27:32.947 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=&lt;masked&gt;}
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................null
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................&quot;jdbc:mysql://172.20.0.50:3306/computer-database-db?zeroDateTimeBehavior=convertToNull&quot;
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
17:27:32.948 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
17:27:32.949 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................1000
17:27:32.949 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................null
17:27:32.949 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
17:27:32.949 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................1000
17:27:32.949 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................&lt;masked&gt;
17:27:32.949 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................&quot;HikariPool-1&quot;
17:27:32.950 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
17:27:32.950 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
17:27:32.950 [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
17:27:32.950 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................null
17:27:32.950 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............null
17:27:32.950 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................&quot;admincdb&quot;
17:27:32.950 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
17:27:32.950 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
17:28:02.971 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
17:28:02.972 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before closing stats (total=0, active=0, idle=0, waiting=0)
17:28:02.972 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After closing stats (total=0, active=0, idle=0, waiting=0)
17:28:02.972 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Closed.
</system-out>
  </testcase>
</testsuite>